/**
 * Deterministic catalog generator.
 *
 * Reads a ResolvedCatalog (built offline from manifest + lock + cache) and
 * writes every output. Generation is a pure function of its inputs:
 *   - stable sort order
 *   - stable, recursively-sorted JSON keys
 *   - LF line endings, UTF-8, trailing newline
 *   - no wall-clock timestamps anywhere
 *
 * Atomicity: everything is staged in a temp dir first. Only after the full
 * build succeeds do we swap it into place, so a failure leaves the committed
 * outputs untouched.
 */
import { mkdir, writeFile, rm, cp, readFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { join, relative, dirname } from "node:path";
import { createHash } from "node:crypto";
import type {
  Catalog,
  CatalogSkillEntry,
  Lockfile,
  ResolvedSkill,
} from "./types.ts";
import type { ResolvedCatalog } from "./resolver.ts";
import { skillSortKey } from "./resolver.ts";
import { info } from "./log.ts";
import type { DiffReport } from "./diff.ts";

const CATALOG_SCHEMA_VERSION = 1;
const GENERATED_BANNER = "<!-- AUTO-GENERATED by `bun run catalog:generate` — do not edit directly. -->";

/** Recursively sort object keys for stable JSON. Arrays keep order. */
export function stableJson(value: unknown): unknown {
  if (Array.isArray(value)) return value.map(stableJson);
  if (value && typeof value === "object") {
    const out: Record<string, unknown> = {};
    for (const k of Object.keys(value as Record<string, unknown>).sort()) {
      out[k] = stableJson((value as Record<string, unknown>)[k]);
    }
    return out;
  }
  return value;
}

export function jsonString(value: unknown): string {
  return JSON.stringify(stableJson(value), null, 2) + "\n";
}

/** Sanitize a string into a collision-safe path segment. */
function safeSeg(s: string): string {
  const seg = s.replace(/[^a-z0-9-]+/gi, "-").replace(/^-+|-+$/g, "").toLowerCase();
  return seg || "unnamed";
}

export function skillPagePath(skill: ResolvedSkill): string {
  return `docs/skills/${safeSeg(skill.sourceId)}/${safeSeg(skill.skillName)}.md`;
}

function sortedSkills(skills: ResolvedSkill[]): ResolvedSkill[] {
  return [...skills].sort((a, b) => skillSortKey(a).localeCompare(skillSortKey(b)));
}

// ---------------------------------------------------------------------------
// Per-skill page
// ---------------------------------------------------------------------------

export function renderSkillPage(skill: ResolvedSkill): string {
  const lines: string[] = [];
  lines.push(GENERATED_BANNER);
  lines.push(`<!-- Regenerate: bun run catalog:generate -->`);
  lines.push(`<!-- Source: ${skill.sourceId} · revision ${skill.resolvedRevision ?? "n/a"} -->`);
  lines.push(`<!-- Redistribution: ${skill.license.redistribution} (declared ${skill.license.declared}, detected ${skill.license.detected}) -->`);
  lines.push("");
  lines.push(`# ${skill.canonicalInvocation}`);
  lines.push("");

  if (skill.unresolvedReason) {
    lines.push(`> **Runtime-only component** — not deterministically resolvable from a git ref.`);
    lines.push(`> ${skill.unresolvedReason}`);
    lines.push("");
  }

  const meta: Array<[string, string]> = [];
  if (skill.skillName) meta.push(["skill-name", skill.skillName]);
  meta.push(["source", skill.sourceId]);
  meta.push(["pack", skill.pack]);
  if (skill.repo) meta.push(["repo", skill.repo]);
  if (skill.ref) meta.push(["ref", skill.ref]);
  if (skill.resolvedRevision) meta.push(["resolved-revision", skill.resolvedRevision]);
  meta.push(["relative-path", skill.relativePath || "(runtime)"]);
  if (skill.version) meta.push(["version", skill.version]);
  if (skill.preambleTier !== undefined) meta.push(["preamble-tier", String(skill.preambleTier)]);
  if (skill.allowedTools?.length) meta.push(["allowed-tools", skill.allowedTools.join(", ")]);
  if (skill.disallowedTools?.length) meta.push(["disallowed-tools", skill.disallowedTools.join(", ")]);
  meta.push(["digest", `sha256:${skill.digest}`]);
  meta.push(["redistribution", skill.license.redistribution]);
  if (skill.license.note) meta.push(["license-note", skill.license.note]);
  if (skill.security.flags.length) meta.push(["security-flags", skill.security.flags.join(", ")]);

  lines.push("| field | value |");
  lines.push("| --- | --- |");
  for (const [k, v] of meta) lines.push(`| ${k} | ${v} |`);
  lines.push("");

  if (skill.description) {
    lines.push("## Description");
    lines.push("");
    lines.push(skill.description);
    lines.push("");
  }
  if (skill.whenToUse) {
    lines.push("## When to use");
    lines.push("");
    lines.push(skill.whenToUse);
    lines.push("");
  }

  if (skill.license.redistribution === "full" && skill.body.trim()) {
    lines.push("## Original frontmatter");
    lines.push("");
    lines.push("```yaml");
    lines.push(skill.rawFrontmatter || "(none)");
    lines.push("```");
    lines.push("");
    lines.push("## Instructions");
    lines.push("");
    lines.push(skill.body.trim());
    lines.push("");
  } else {
    lines.push("## Content");
    lines.push("");
    lines.push("Full body omitted from this catalog (redistribution is metadata-only).");
    if (skill.repo && skill.resolvedRevision) {
      lines.push(`Read it at the immutable revision: ${skill.repo}/tree/${skill.resolvedRevision}/${skill.relativePath.replace(/\/[^/]*$/, "")}`);
    }
    lines.push("");
  }

  if (skill.warnings.length) {
    lines.push("## Validation warnings");
    lines.push("");
    for (const w of skill.warnings) lines.push(`- ${w}`);
    lines.push("");
  }

  lines.push("---");
  lines.push("");
  lines.push("*Generated by the Skills Catalog resolver. Edit the upstream source, then rerun `bun run catalog:generate`.*");
  lines.push("");
  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// Index (SKILLS_CATALOG.md)
// ---------------------------------------------------------------------------

export function renderIndex(resolved: ResolvedCatalog): string {
  const skills = sortedSkills(resolved.skills);
  const lines: string[] = [GENERATED_BANNER, "<!-- Regenerate: bun run catalog:generate -->", ""];
  lines.push("# Skills Catalog");
  lines.push("");
  lines.push(`Generated index of every Claude Code skill, command, and runtime component represented by \`furkankoykiran/.claude\`.`);
  lines.push(`Resolver version ${resolved.lock.resolverVersion} · schema v${CATALOG_SCHEMA_VERSION}.`);
  lines.push("");
  lines.push(`- **Sources:** ${resolved.sourceMeta.length}`);
  lines.push(`- **Skills / entries:** ${skills.length}`);
  lines.push(`- **Redistributable (full body):** ${skills.filter((s) => s.license.redistribution === "full").length}`);
  lines.push(`- **Runtime-only:** ${resolved.sourceMeta.filter((s) => s.runtimeOnly).length}`);
  lines.push("");

  // Group by source in stable (id) order.
  const bySource = new Map<string, ResolvedSkill[]>();
  for (const s of skills) {
    const arr = bySource.get(s.sourceId) ?? [];
    arr.push(s);
    bySource.set(s.sourceId, arr);
  }
  const sourceOrder = [...resolved.sourceMeta].sort((a, b) => a.id.localeCompare(b.id));

  for (const sm of sourceOrder) {
    const arr = (bySource.get(sm.id) ?? []).sort((a, b) => a.canonicalInvocation.localeCompare(b.canonicalInvocation));
    const meta = resolved.sourceMeta.find((m) => m.id === sm.id)!;
    lines.push(`## ${meta.displayName}`);
    lines.push("");
    lines.push(`type: \`${meta.type}\` · pack: \`${meta.pack}\` · skills: ${arr.length} · redistribution: ${meta.redistribution}`);
    if (meta.repo && meta.resolvedRevision) {
      lines.push(`repo: ${meta.repo} · ref: \`${meta.ref}\` · revision: \`${meta.resolvedRevision.slice(0, 12)}\``);
    }
    if (meta.runtimeOnly) lines.push(`_Runtime-only — see notes below._`);
    lines.push("");
    if (arr.length === 0) {
      lines.push("_(no resolvable skills)_");
      lines.push("");
      continue;
    }
    lines.push("| invocation | description | redistribution |");
    lines.push("| --- | --- | --- |");
    for (const s of arr) {
      const desc = (s.description ?? "").replace(/\|/g, "\\|").replace(/\n/g, " ").slice(0, 120);
      // relative() from the CONTAINING DIRECTORY. Passing the file path
      // itself treats the filename as a directory and emits one extra "..",
      // which is why every link in the published SKILLS_CATALOG.md pointed
      // above the repository root.
      const link = `[${s.canonicalInvocation}](${relative(dirname(`${GENERATED_DIR}/SKILLS_CATALOG.md`), skillPagePath(s))})`;
      lines.push(`| ${link} | ${desc} | ${s.license.redistribution} |`);
    }
    lines.push("");
  }

  if (resolved.warnings.length) {
    lines.push("## Warnings");
    lines.push("");
    for (const w of [...new Set(resolved.warnings)].sort()) lines.push(`- ${w}`);
    lines.push("");
  }

  lines.push("---");
  lines.push("");
  lines.push("*Regenerate with `bun run catalog:generate`. See `docs/catalog-architecture.md` for the discovery model.*");
  lines.push("");
  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// Machine-readable catalog
// ---------------------------------------------------------------------------

export function buildCatalogJson(resolved: ResolvedCatalog): Catalog {
  const skills = sortedSkills(resolved.skills);
  const entries: CatalogSkillEntry[] = skills.map((s) => ({
    canonicalInvocation: s.canonicalInvocation,
    namespacedInvocations: s.namespacedInvocations,
    skillName: s.skillName,
    sourceId: s.sourceId,
    pack: s.pack,
    sourceType: s.sourceType,
    repo: s.repo,
    ref: s.ref,
    resolvedRevision: s.resolvedRevision,
    relativePath: s.relativePath,
    description: s.description,
    whenToUse: s.whenToUse,
    version: s.version,
    allowedTools: s.allowedTools,
    disallowedTools: s.disallowedTools,
    preambleTier: s.preambleTier,
    digest: s.digest,
    license: s.license,
    security: s.security,
    redistribution: s.license.redistribution,
    generated: s.generated,
    unresolvedReason: s.unresolvedReason,
    warnings: s.warnings,
    frontmatter: s.frontmatter,
    fullPagePath: skillPagePath(s),
  }));

  return {
    schemaVersion: CATALOG_SCHEMA_VERSION,
    resolverVersion: resolved.lock.resolverVersion,
    generated: true,
    totals: {
      sources: resolved.sourceMeta.length,
      skills: entries.length,
      redistributable: entries.filter((e) => e.redistribution === "full").length,
      runtimeOnly: resolved.sourceMeta.filter((s) => s.runtimeOnly).length,
      warnings: resolved.warnings.length,
    },
    sources: [...resolved.sourceMeta]
      .sort((a, b) => a.id.localeCompare(b.id))
      .map((s) => ({
        id: s.id,
        type: s.type,
        displayName: s.displayName,
        pack: s.pack,
        repo: s.repo,
        ref: s.ref,
        resolvedRevision: s.resolvedRevision,
        skillCount: s.skillCount,
        redistribution: s.redistribution,
        runtimeOnly: s.runtimeOnly,
      })),
    skills: entries,
  };
}

// ---------------------------------------------------------------------------
// Portable single-file export
// ---------------------------------------------------------------------------

export function renderPortable(resolved: ResolvedCatalog): string {
  const skills = sortedSkills(resolved.skills);
  const lines: string[] = [
    GENERATED_BANNER,
    "<!-- Single-file portable export of the Skills Catalog. -->",
    "<!-- Regenerate: bun run catalog:generate -->",
    "",
    "# claude_code_skills.md",
    "",
    `Bundled export of every redistributable skill page in \`furkankoykiran/.claude\`.`,
    `Resolver version ${resolved.lock.resolverVersion} · ${skills.length} entries.`,
    "",
  ];
  // Include full pages only where redistribution is permitted.
  const redistributable = skills.filter((s) => s.license.redistribution === "full");
  const omitted = skills.length - redistributable.length;
  lines.push(`Included full pages: ${redistributable.length}. Omitted (metadata-only/runtime): ${omitted}.`);
  lines.push("");
  for (const s of skills) {
    lines.push(renderSkillPage(s));
  }
  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// SHA256SUMS
// ---------------------------------------------------------------------------

async function hashFile(p: string): Promise<string> {
  const buf = await readFile(p);
  return createHash("sha256").update(buf).digest("hex");
}

export async function writeShaSums(stagingDir: string, relFiles: string[]): Promise<string> {
  const lines: string[] = [];
  for (const rel of [...relFiles].sort()) {
    const hash = await hashFile(join(stagingDir, rel));
    lines.push(`${hash}  ${rel}`);
  }
  return lines.join("\n") + "\n";
}

// ---------------------------------------------------------------------------
// Atomic write-all
// ---------------------------------------------------------------------------

export interface GenerateOptions {
  outDir: string; // repo root
  lock: Lockfile;
  diff?: DiffReport | null;
}

/**
 * Where the generated catalog artifacts live in the repository.
 *
 * Staging stays FLAT (bare filenames) because SHA256SUMS records bare names and
 * those names are the public GitHub Release asset names. Only the swap step
 * places them under this directory, so the release contract is unaffected by
 * where they sit in the tree.
 */
export const GENERATED_DIR = "catalog/generated";

const TOP_LEVEL_OUTPUTS = [
  "SKILLS_CATALOG.md",
  "claude_code_skills.md",
  "skills-catalog.json",
  "skills-catalog-diff.json",
  "catalog-change-report.md",
];

const SHA_ASSETS = [
  "claude_code_skills.md",
  "SKILLS_CATALOG.md",
  "skills-catalog.json",
  "skills-source.lock.json",
  "skills-catalog-diff.json",
  "catalog-change-report.md",
];

/** Build every output file into `stagingDir` (no swap, no repo mutation). */
export async function stageOutputs(
  resolved: ResolvedCatalog,
  stagingDir: string,
  opts: { lock: Lockfile; diff?: DiffReport | null },
): Promise<string[]> {
  await rm(stagingDir, { recursive: true, force: true });
  await mkdir(join(stagingDir, "docs", "skills"), { recursive: true });

  const written: string[] = [];

  for (const s of sortedSkills(resolved.skills)) {
    const rel = skillPagePath(s);
    const abs = join(stagingDir, rel);
    await mkdir(join(abs, ".."), { recursive: true });
    await writeFile(abs, renderSkillPage(s), "utf8");
    written.push(rel);
  }

  await writeFile(join(stagingDir, "SKILLS_CATALOG.md"), renderIndex(resolved), "utf8");
  await writeFile(join(stagingDir, "claude_code_skills.md"), renderPortable(resolved), "utf8");
  await writeFile(join(stagingDir, "skills-catalog.json"), jsonString(buildCatalogJson(resolved)), "utf8");
  await writeFile(join(stagingDir, "skills-source.lock.json"), jsonString(opts.lock), "utf8");
  if (opts.diff) {
    await writeFile(join(stagingDir, "skills-catalog-diff.json"), jsonString(opts.diff), "utf8");
    await writeFile(join(stagingDir, "catalog-change-report.md"), renderChangeReport(opts.diff), "utf8");
  } else {
    await writeFile(
      join(stagingDir, "skills-catalog-diff.json"),
      jsonString({ schemaVersion: 1, base: null, summary: { added: 0, updated: 0, removed: 0, renamed: 0, licenseRestricted: 0, runtimeOnly: 0, securitySensitive: 0, manualReviewRequired: false }, changes: [] }),
      "utf8",
    );
    await writeFile(
      join(stagingDir, "catalog-change-report.md"),
      `# Catalog change report\n\n${GENERATED_BANNER}\n\nNo base catalog supplied; this is the initial catalog (everything is new).\n`,
      "utf8",
    );
  }
  for (const f of TOP_LEVEL_OUTPUTS) written.push(f);
  written.push("skills-source.lock.json");

  const sums = await writeShaSums(stagingDir, SHA_ASSETS);
  await writeFile(join(stagingDir, "SHA256SUMS"), sums, "utf8");
  written.push("SHA256SUMS");
  return written;
}

export async function generateAll(
  resolved: ResolvedCatalog,
  opts: GenerateOptions,
): Promise<{ written: string[] }> {
  const staging = join(opts.outDir, "catalog", ".tmp", `gen-${process.pid}`);
  const written = await stageOutputs(resolved, staging, { lock: opts.lock, diff: opts.diff });

  // ---- Swap: only after the full build succeeded. ----
  info(`swapping ${written.length} generated files into ${opts.outDir}`);
  const realDocsSkills = join(opts.outDir, "docs", "skills");
  await rm(realDocsSkills, { recursive: true, force: true });
  if (existsSync(join(staging, "docs", "skills"))) {
    await mkdir(join(realDocsSkills, ".."), { recursive: true });
    await cp(join(staging, "docs", "skills"), realDocsSkills, { recursive: true });
  }
  // Generated artifacts land under catalog/generated/; the lock stays at the
  // repository root next to the manifest it locks.
  await mkdir(join(opts.outDir, GENERATED_DIR), { recursive: true });
  for (const f of [...TOP_LEVEL_OUTPUTS, "SHA256SUMS"]) {
    await cp(join(staging, f), join(opts.outDir, GENERATED_DIR, f));
  }
  await cp(join(staging, "skills-source.lock.json"), join(opts.outDir, "skills-source.lock.json"));

  await rm(staging, { recursive: true, force: true });
  return { written };
}

function renderChangeReport(diff: DiffReport): string {
  const lines: string[] = [GENERATED_BANNER, "", "# Catalog change report", ""];
  lines.push(`- added: ${diff.summary.added}`);
  lines.push(`- updated: ${diff.summary.updated}`);
  lines.push(`- removed: ${diff.summary.removed}`);
  lines.push(`- renamed: ${diff.summary.renamed}`);
  lines.push(`- license-restricted: ${diff.summary.licenseRestricted}`);
  lines.push(`- runtime-only: ${diff.summary.runtimeOnly}`);
  lines.push(`- security-sensitive: ${diff.summary.securitySensitive}`);
  lines.push(`- **manual-review-required: ${diff.summary.manualReviewRequired}**`);
  lines.push("");
  const section = (title: string, items: Array<{ key: string; detail?: string }>) => {
    if (!items.length) return;
    lines.push(`## ${title} (${items.length})`);
    lines.push("");
    for (const it of items) lines.push(`- \`${it.key}\`${it.detail ? ` — ${it.detail}` : ""}`);
    lines.push("");
  };
  section("Added", diff.changes.filter((c) => c.kind === "added"));
  section("Updated", diff.changes.filter((c) => c.kind === "updated"));
  section("Removed", diff.changes.filter((c) => c.kind === "removed"));
  section("Renamed", diff.changes.filter((c) => c.kind === "renamed"));
  section("Security-sensitive", diff.changes.filter((c) => c.securitySensitive));
  section("Manual-review-required", diff.changes.filter((c) => c.manualReviewRequired));
  return lines.join("\n") + "\n";
}